CREATE TABLE IF NOT EXISTS Competitions(
    -- Remember to refer to your proposal for your exact columns
    id int AUTO_INCREMENT PRIMARY KEY,
    `name` varchar(240) not null,
    min_participants int DEFAULT 3,
    current_participants int default 0,
    join_fee int default 1,
    starting_reward int DEFAULT 1,
    current_reward int DEFAULT (starting_reward),
    did_calc BOOLEAN DEFAULT false,
    paid_out BOOLEAN DEFAULT false,
    duration int default 3,
    created_by int,
    cost_to_create int default (1+starting_reward+join_fee),
    first_place_per int,
    second_place_per int,
    third_place_per int,
    min_score int DEFAULT 0,
    expires TIMESTAMP DEFAULT (DATE_ADD(CURRENT_TIMESTAMP, INTERVAL duration DAY)),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP on update CURRENT_TIMESTAMP,
    FOREIGN KEY(created_by) REFERENCES Users(id),
    check (min_score >= 0),
    check (first_place_per + second_place_per + third_place_per = 100),
    check (starting_reward >= 1),
    check (current_reward >= starting_reward),
    check (min_participants >= 3),
    check (current_participants >= 0),
    check(join_fee >= 0)
)